### ISSUE TITLE
Update translations for DE, NL, SV

### ISSUE THREAD

**Issue by kimmoli** [kimmoli/paint#28]

**Comment by kimmoli** [comment]
![20150321142927](https://cloud.githubusercontent.com/assets/4472660/6765025/f982f678-cfd6-11e4-948b-ee06823d3ab4.png)

**Comment by kimmoli** [comment]
![20150321142927](https://cloud.githubusercontent.com/assets/4472660/6765029/1243e1f4-cfd7-11e4-9a40-8a9a8c7b0f11.png)

**Comment by jklingen** [comment]
German: #29 :)

**Comment by kimmoli** [comment]
Svenska 4ae56bb652afd9c9fe702caed2d8e44ff74a3348

**Comment by kimmoli** [comment]
Translations now in Transifex, https://www.transifex.com/projects/p/paint
