### ISSUE TITLE
layer system/image import

### ISSUE THREAD

**Issue by newincpp** [kimmoli/paint#41]
For now paint is the only image manipulator on Sailfish for now it would be great to make it better (spatially when the the jolla tablet will be release it would be really cool to have a cool to use image manipulator) and like for the undo/redo feature a layer system could be awesome.

I'm talking about the same layer system than have gimp, krita or even inkscape which is:
A texture independent from others textures and draw in a specific order.
Obviously we should be able to move scale and rotate any layer independently 

Importing an image (jpg, png and tga at the beginning) in a new layer could be a really great addition.

PS: I can help you with openGL if you need it...

**Comment by kimmoli** [comment]
Image import with scale/rotate implemented

**Comment by newincpp** [comment]
Awesome! =D I can't wait to see it on the next update !
